---
- hosts: db
- name: database assignment
  ansible.builtin.import_playbook: ../static-assignments/database.yml

- hosts: nginx
- name: nginx assignment
  ansible.builtin.import_playbook: ../static-assignments/nginx.yml

- hosts: tooling
- name: deploy tooling website
  ansible.builtin.import_playbook: ../static-assignments/webserver.yml

- hosts: artifactory
- name: artifactory assignment
  ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

- hosts: todo
- name: Deploy the todo application
  ansible.builtin.import_playbook: ../static-assignments/deployment.yml

- hosts: sonarqube
- name: sonar assignment
  ansible.builtin.import_playbook: ../static-assignments/sonarqube.yml

